### ISSUE TITLE
购票选择问题

### ISSUE THREAD

**Issue by ZhongqiXiao** [Woo-Long/12306-electron#2]
在购票的时候，勾选车次再添加任务，会提示请选择车次，需要再重新勾选一下车次，才可以选座位类别，希望可以改进一下。期待添加以下功能：
1.返回功能，选错了方便重选。
2.动车和高铁的选座位功能，这个12306上面已经开放
3.购票日期的限制，日期只能选到当前已经可以购买或当天放票的时期

感谢作者制作这么一款软件！

**Comment by long-woo** [comment]
非常感谢你的反馈，后续会优化和增加一些功能，敬请期待
