### ISSUE TITLE
window10系统下无法打包

### ISSUE THREAD

**Issue by redasm** [Woo-Long/12306-electron#8]
![default](https://user-images.githubusercontent.com/9164386/47732065-627c6e00-dca0-11e8-825e-7cdd131d24ed.PNG)
一直有这个错误，build出的exe白屏

**Comment by long-woo** [comment]
在主进程/src/main/index.js中`mainWindow.openDevTools()`，然后再build，看一下控制台错误信息是什么
https://github.com/SimulatedGREG/electron-vue/issues/430
