### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by redasm** [Woo-Long/12306-electron#9]
![1](https://user-images.githubusercontent.com/9164386/47965176-c88d3a80-e07e-11e8-8388-68aafbd783e8.PNG)
![default](https://user-images.githubusercontent.com/9164386/47965177-c9be6780-e07e-11e8-9b62-a7e802ab7793.PNG)
网上的解决方法
npm run dev 可以看到，但是通过dist文件下的index.html直接打开没显示，没看到  
webpack.prod.conf.js 中output添加参数publicPath:'./'
在webpack.base.conf.js里
publicPath: process.env.NODE_ENV === 'production'
      ? './' +config.build.assetsPublicPath
      : './' + config.dev.assetsPublicPath
项目中没找到这两个文件

**Comment by long-woo** [comment]
webpack.base.conf.js、webpack.prod.conf.js这两个文件不是electron-vue模板中的，而是vue官方的工程模板。
先将node_modules删除，重新`yarn` 或`npm install`试试
